---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zjoawlrttx/coachcem.com/1hari1/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R index-b.html $DEPLOYPATH
    - /bin/cp -R terma.html $DEPLOYPATH
    - /bin/cp -R terima-kasih.html $DEPLOYPATH
    - /bin/cp -R coach-cem.jpg $DEPLOYPATH
    - /bin/cp -R ebook-cover.jpg $DEPLOYPATH
    - /bin/cp -R og-image.jpg $DEPLOYPATH
    - /bin/cp -R checkout.html $DEPLOYPATH
    - /bin/cp -R create-purchase.php $DEPLOYPATH
    - /bin/cp -R chip-callback.php $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/phpmailer/src
    - /bin/cp -R phpmailer/src/. $DEPLOYPATH/phpmailer/src
